name: CSharpier
on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  check_formatting:
    runs-on: very-cool-self-hosted-mbanas
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        run: |
          sudo add-apt-repository ppa:dotnet/backports \
          && sudo apt-get update \
          && sudo apt-get install -y dotnet-sdk-9.0

      - run: |
          dotnet tool restore
          dotnet csharpier check .
