name: Upload dotnet tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"

      - name: Checkout action v4
        uses: actions/checkout@v4

      - name: Checkout action v2
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
